//! Round-trip regression harness for subtitle format parsers and serializers.
//!
//! For every fixture under `tests/fixtures/formats/<format>/`, this harness:
//! 1. Loads the fixture via [`FormatManager::load_subtitle`] (which performs
//!    encoding detection / BOM stripping at the file layer).
//! 2. Performs lightweight structural sanity checks on the resulting
//!    [`Subtitle`].
//! 3. Re-serializes via the matching [`SubtitleFormat`] implementation.
//! 4. Compares the serialized bytes byte-for-byte against the committed
//!    `<fixture>.expected` companion file.
//!
//! `<fixture>.expected` files are NOT hand-authored — they are generated by
//! the ignored test [`generate_expected_outputs`] in this same file. To
//! refresh them, run:
//!
//! ```bash
//! cargo nextest run --test format_roundtrip_tests \
//!     -- --ignored generate_expected_outputs
//! ```
//!
//! `.expected` files capture today's serializer output (canonical form),
//! NOT the original fixture bytes — they exist to lock serializer behavior
//! across the refactor.

use std::path::{Path, PathBuf};

use pretty_assertions::assert_eq;
use subx_core::core::formats::manager::FormatManager;
use subx_core::core::formats::{Subtitle, SubtitleFormat, SubtitleFormatType};

/// Resolve `tests/fixtures/formats/<format>` regardless of cwd.
fn fixtures_dir(format_subdir: &str) -> PathBuf {
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    manifest
        .join("tests")
        .join("fixtures")
        .join("formats")
        .join(format_subdir)
}

/// Collect every input fixture (skip `.expected` companions).
fn list_fixtures(format_subdir: &str) -> Vec<PathBuf> {
    let dir = fixtures_dir(format_subdir);
    let mut out = Vec::new();
    for entry in std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("read_dir {} failed: {}", dir.display(), e))
    {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        if path
            .extension()
            .and_then(|s| s.to_str())
            .is_some_and(|s| s.eq_ignore_ascii_case("expected"))
        {
            continue;
        }
        out.push(path);
    }
    out.sort();
    out
}

/// Match a fixture path back to a concrete [`SubtitleFormat`] impl.
fn format_for(format_subdir: &str) -> Box<dyn SubtitleFormat> {
    match format_subdir {
        "srt" => Box::new(subx_core::core::formats::srt::SrtFormat),
        "ass" => Box::new(subx_core::core::formats::ass::AssFormat),
        "vtt" => Box::new(subx_core::core::formats::vtt::VttFormat),
        "sub" => Box::new(subx_core::core::formats::sub::SubFormat),
        other => panic!("unknown fixture subdir: {}", other),
    }
}

fn expected_format(subdir: &str) -> SubtitleFormatType {
    match subdir {
        "srt" => SubtitleFormatType::Srt,
        "ass" => SubtitleFormatType::Ass,
        "vtt" => SubtitleFormatType::Vtt,
        "sub" => SubtitleFormatType::Sub,
        other => panic!("unknown fixture subdir: {}", other),
    }
}

/// Parse a fixture via the public `FormatManager` entry point that mirrors
/// production file-loading (encoding detection + BOM strip + parse_auto).
fn parse_fixture(path: &Path) -> Subtitle {
    let manager = FormatManager::new();
    manager
        .load_subtitle(path)
        .unwrap_or_else(|e| panic!("load_subtitle({}) failed: {}", path.display(), e))
}

/// Per-fixture semantic expectations. Locks the *in-memory* `Subtitle`
/// shape so a regenerated `.expected` file alone cannot mask a parser
/// regression. CRLF entries reflect known SRT/VTT pre-existing quirks
/// (see Decision 7 in the change design).
fn expected_entry_count(fixture: &Path) -> Option<usize> {
    let name = fixture.file_name()?.to_str()?;
    Some(match name {
        // SRT — 2 cue blocks for both LF/BOM and CRLF after the
        // line-ending-tolerant block splitter landed; CRLF inputs
        // now parse to the same entry count as their LF counterpart.
        "basic.srt" | "bom.srt" | "basic.crlf.srt" => 2,

        // ASS — line-based parser, CRLF and LF parse identically.
        "basic.ass" | "basic.crlf.ass" | "bom.ass" => 2,

        // VTT — 2 cues for LF/BOM and (after the line-ending-tolerant
        // splitter landed) for CRLF as well.
        "basic.vtt" | "bom.vtt" | "basic.crlf.vtt" => 2,

        // SUB — line-based, CRLF and LF parse identically.
        "basic.sub" | "basic.crlf.sub" => 2,

        _ => return None,
    })
}

fn run_roundtrip(format_subdir: &str) {
    let format = format_for(format_subdir);
    let expected_fmt = expected_format(format_subdir);

    let fixtures = list_fixtures(format_subdir);
    assert!(
        !fixtures.is_empty(),
        "no fixtures found in tests/fixtures/formats/{}",
        format_subdir
    );

    for fixture in fixtures {
        let subtitle = parse_fixture(&fixture);

        // ── Structural sanity checks ────────────────────────────────────────
        assert_eq!(
            subtitle.format,
            expected_fmt,
            "{} parsed to wrong format variant",
            fixture.display()
        );
        // Per-fixture entry-count lock. Without this assertion a regenerated
        // `.expected` could silently hide a parser that drops or duplicates
        // cues. CRLF expectations encode known SRT/VTT pre-existing quirks
        // (see Decision 7 in the change design); fixing them is deferred to
        // a follow-up change.
        if let Some(n) = expected_entry_count(&fixture) {
            assert_eq!(
                subtitle.entries.len(),
                n,
                "{} parsed to {} entries; expected {} (per-fixture semantic lock)",
                fixture.display(),
                subtitle.entries.len(),
                n
            );
        }
        for entry in &subtitle.entries {
            assert!(
                entry.is_valid_timing(),
                "{} contains entry with invalid timing: {:?}",
                fixture.display(),
                entry
            );
        }

        // ── Re-serialize and compare to .expected ───────────────────────────
        let actual = format
            .serialize(&subtitle)
            .unwrap_or_else(|e| panic!("serialize({}) failed: {}", fixture.display(), e));

        let expected_path = expected_path_for(&fixture);
        let expected_bytes = std::fs::read(&expected_path).unwrap_or_else(|e| {
            panic!(
                "missing expected fixture {} (regenerate with the ignored \
                 generator test): {}",
                expected_path.display(),
                e
            )
        });
        let expected_str = String::from_utf8(expected_bytes).unwrap_or_else(|e| {
            panic!(
                "expected fixture {} is not valid UTF-8: {}",
                expected_path.display(),
                e
            )
        });

        assert_eq!(
            actual,
            expected_str,
            "round-trip drift for fixture {}",
            fixture.display()
        );
    }
}

/// Build `<fixture>.expected` next to the fixture (e.g. `basic.srt.expected`).
fn expected_path_for(fixture: &Path) -> PathBuf {
    let mut name = fixture
        .file_name()
        .expect("fixture file name")
        .to_os_string();
    name.push(".expected");
    fixture.with_file_name(name)
}

// ── Per-format round-trip tests ─────────────────────────────────────────────

#[test]
fn srt_fixtures_roundtrip() {
    run_roundtrip("srt");
}

#[test]
fn ass_fixtures_roundtrip() {
    run_roundtrip("ass");
}

#[test]
fn vtt_fixtures_roundtrip() {
    run_roundtrip("vtt");
}

#[test]
fn sub_fixtures_roundtrip() {
    run_roundtrip("sub");
}

// ── Expected-output generator (ignored) ─────────────────────────────────────

/// One-shot helper to (re)generate every `<fixture>.expected` file by running
/// the current production serializer against each parsed fixture and writing
/// the bytes to disk. Run only when intentional serializer output changes
/// land; commit the resulting `.expected` files.
#[test]
#[ignore = "regenerates committed .expected fixtures; run on demand"]
fn generate_expected_outputs() {
    for subdir in ["srt", "ass", "vtt", "sub"] {
        let format = format_for(subdir);
        for fixture in list_fixtures(subdir) {
            let subtitle = parse_fixture(&fixture);
            let serialized = format
                .serialize(&subtitle)
                .unwrap_or_else(|e| panic!("serialize({}): {}", fixture.display(), e));
            let target = expected_path_for(&fixture);
            std::fs::write(&target, serialized.as_bytes())
                .unwrap_or_else(|e| panic!("write {}: {}", target.display(), e));
            eprintln!("regenerated {}", target.display());
        }
    }
}
